Exclude commons-beanutils-core because of:
[ERROR] concurrentSettingTest(org.apache.zeppelin.jdbc.JDBCInterpreterTest)  Time elapsed: 0.224 s  <<< ERROR!
java.lang.NoSuchMethodError: org.apache.commons.beanutils.PropertyUtilsBean.addBeanIntrospector(Lorg/apache/commons/beanutils/BeanIntrospector;)V
	at org.apache.zeppelin.jdbc.JDBCInterpreterTest.concurrentSettingTest(JDBCInterpreterTest.java:463)